version: '3'

services:
  frontend:
    build:
      context: ./stock-researcher
      # Pass the API URL as a build argument
      args:
        REACT_APP_API_URL: http://localhost/api
    ports:
      - "80:80"
    depends_on:
      - backend
    # No longer need runtime environment variable here for React App
    # environment:
    #   - REACT_APP_API_URL=http://localhost/api
    networks:
      - app-network

  backend:
    build:
      context: ./stock-researcher-backend
    ports:
      - "5001:5001"
    # Pass the API keys from the host environment to the container
    environment:
      - PORT=5001
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
      - TIINGO_API_KEY=0be74c81ad01d25c6b2fa702a38cab425fb0246c
      - GEMINI_API_KEY=AIzaSyCfm2xX5Lsnpcq18u4Hzv3zbbXkEFbHn44
    networks:
      - app-network

# Define the network used by all services
networks:
  app-network:
    driver: bridge 